name: "Install LLZK"
description: "Builds and installs the LLZK library from source"
inputs:
  ref:
    description: "Commit or tag used for building"
    required: true
  root:
    description: "Where the library will be cloned"
    default: "./llzk-lib"
  type:
    description: "CMake build type"
    default: "Debug"
  mlir-dir:
    description: "Directory where MLIR/LLVM is installed"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: project-llzk/llzk-lib
        ref: ${{ inputs.ref }}
        path: ${{ inputs.root }}
        fetch-depth: 1
    - name: "Cache LLZK build"
      id: cache-llzk
      uses: actions/cache@v4
      with:
        path: ${{ inputs.root }}/build
        key: ${{ runner.os }}-llzk-${{ inputs.ref }}-${{ inputs.type }}-${{ inputs.mlir-dir }}
    - name: "Configure CMake"
      if: steps.cache-llzk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake -B $_ROOT/build \
          -S $_ROOT \
          -DCMAKE_INSTALL_PREFIX=$_ROOT/build/install \
          -DCMAKE_PREFIX_PATH=$_MLIR_DIR \
          -DCMAKE_BUILD_TYPE=$_BUILD_TYPE \
          -DLLZK_VERSION_OVERRIDE=1.0.0 \
          -DBUILD_TESTING=OFF \
          -DCMAKE_CXX_FLAGS="-Wno-error=shadow"
      env:
        _ROOT: ${{ inputs.root }}
        _MLIR_DIR: ${{ inputs.mlir-dir }}
        _BUILD_TYPE: ${{ inputs.type }}
    - name: "Build"
      if: steps.cache-llzk.outputs.cache-hit != 'true'
      shell: bash
      run: cmake --build $_ROOT/build --parallel 2
      env:
        _ROOT: ${{ inputs.root }}
    - name: "Install"
      if: steps.cache-llzk.outputs.cache-hit != 'true'
      shell: bash
      run: cmake --install $_ROOT/build
      env:
        _ROOT: ${{ inputs.root }}
    - name: "Export LLZK environment"
      shell: bash
      run: echo LLZK_SYS_10_PREFIX=$(realpath $_ROOT/build/install) >> $GITHUB_ENV
      env:
        _ROOT: ${{ inputs.root }}
